# Utilisez une image Node.js en tant qu'image de base
FROM node:latest

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le package.json et le package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez tous les fichiers source dans le répertoire de travail
COPY . .

# Construisez l'application React
# RUN npm run start
# RUN npm run build

# Commande pour démarrer l'application React (elle dépendra de votre application)
CMD ["npm", "run", "dev"]
