# Utilisez une image Node.js en tant qu'image de base
FROM node:latest

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le package.json dans le répertoire de travail
COPY package*.json ./

# COPY output.css ./output.css

# Install dependencies
RUN npm install

# Copy all source files into the working directory
COPY . .

CMD ["npm", "run", "build"]





