version: "3.5"
services:
  # Frontend React.js
  frontend:
    build:
      context: ./frontend # Le chemin vers le répertoire du code source React.js
    ports:
      - "3000:3000" # Port pour le serveur de développement React
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    env_file:
      - .env

  # Backend Nest.js
  backend:
    build:
      context: ./backend # Le chemin vers le répertoire du code source Nest.js
    ports:
      - "4000:4000" # Port pour le serveur Nest.js
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./backend:/app/
      - /app/node_modules

  # Serveur nginx
  nginx:
    build:
      context: nginx
    container_name: nginx-dev
    tty: true
    ports:
      - "8000:443"
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  # PostgreSQL
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" # Port pour PostgreSQL
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
