# Utilisez une image de Node.js comme base
FROM node:latest

# Créez un répertoire de travail dans le conteneur
WORKDIR /dist

# Copiez le package.json et le package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances
RUN npm install


# Copiez le code source Nest.js dans le répertoire de travail
COPY . .

# Build the application
RUN npm run build

# Port exposé par l'application Nest.js
EXPOSE 4000

# # Copy the dist directory into the Docker image
COPY dist /app/dist


# Command to start the application
CMD ["npm", "run", "start:prod"]
