# Utilisez une image de Node.js comme base
FROM node:latest

# Créez un répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le package.json et le package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le code source Nest.js dans le répertoire de travail
COPY . .

# Port exposé par l'application Nest.js
EXPOSE 3000

# Commande pour démarrer l'application Nest.js
CMD ["npm","run", "start:dev"]
